"""empty message

Revision ID: 321272bdd25c
Revises: f35a2cebcdc2
Create Date: 2023-10-06 11:11:33.636613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321272bdd25c'
down_revision = 'f35a2cebcdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categroy', sa.Integer(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.drop_column('categroy')

    # ### end Alembic commands ###
