"""empty message

Revision ID: 95070cfd5534
Revises: ad51aad3eb58
Create Date: 2023-09-22 11:10:43.587326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95070cfd5534'
down_revision = 'ad51aad3eb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
