"""empty message

Revision ID: a7670adb4001
Revises: d2e52cede5ef
Create Date: 2023-10-06 11:36:34.781685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7670adb4001'
down_revision = 'd2e52cede5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=False))
        batch_op.drop_column('categroy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categroy', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
