"""empty message

Revision ID: c4123645d178
Revises: 884bbaec07bd
Create Date: 2023-10-06 14:12:49.877293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4123645d178'
down_revision = '884bbaec07bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_comment_voter_comment_id_comment', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_voter_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_voter_pid_comment'), 'comment', ['pid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_voter_uid_user'), 'user', ['uid'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_comment_voter_uid_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_voter_pid_comment'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_voter_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_comment_voter_comment_id_comment', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('pid')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
