"""empty message

Revision ID: d2e52cede5ef
Revises: 321272bdd25c
Create Date: 2023-10-06 11:13:07.617476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e52cede5ef'
down_revision = '321272bdd25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.alter_column('categroy',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.alter_column('categroy',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
