"""empty message

Revision ID: fbaa51eb20e3
Revises: a7670adb4001
Create Date: 2023-10-06 11:39:57.469584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaa51eb20e3'
down_revision = 'a7670adb4001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_posting')
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), server_default='1', nullable=True))
        batch_op.drop_column('categroy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categroy', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_column('category')

    op.create_table('_alembic_tmp_posting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('uid', sa.INTEGER(), nullable=False),
    sa.Column('mod_date', sa.DATETIME(), nullable=True),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
